import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          (),
        ]),
      ),
    );
  }
}

class  extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 401,
          height: 858,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 401,
                height: 858,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 401,
                        height: 858,
                        padding: const EdgeInsets.only(
                          top: 704,
                          left: 24,
                          right: 330,
                          bottom: 106,
                        ),
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(color: Colors.white),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                          ,
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 401,
                        height: 858,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 401,
                                height: 93,
                                padding: const EdgeInsets.only(top: 41, right: 232),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 183,
                                      height: 52,
                                      child: Text(
                                        'Pill check',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 30,
                                          fontFamily: 'Oleo Script Swash Caps',
                                          fontWeight: FontWeight.w400,
                                          height: 0.06,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 780,
                              child: Container(
                                width: 401,
                                height: 78,
                                padding: const EdgeInsets.only(top: 20, bottom: 21),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 37,
                                      height: 37,
                                      decoration: ShapeDecoration(
                                        color: Color(0xFFD9D9D9),
                                        shape: OvalBorder(),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 23,
                              top: 370,
                              child: Container(
                                width: 359,
                                height: 43,
                                padding: const EdgeInsets.only(top: 9, left: 321, right: 8, bottom: 6),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFF585858)),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.end,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 30,
                                      height: double.infinity,
                                      padding: const EdgeInsets.only(top: 2, left: 5, right: 5, bottom: 10),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(color: Colors.white),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          SizedBox(
                                            width: 20,
                                            height: 16,
                                            child: Text(
                                              'x',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: Colors.black,
                                                fontSize: 28,
                                                fontFamily: 'Oleo Script Swash Caps',
                                                fontWeight: FontWeight.w700,
                                                height: 0.03,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 23,
                              top: 413,
                              child: Container(
                                width: 359,
                                height: 293,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFFC4C4C4)),
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 86,
                                      top: 75,
                                      child: SizedBox(
                                        width: 192,
                                        height: 39,
                                        child: Text(
                                          '권한 허용 필요',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 22,
                                            fontFamily: 'Oleo Script Swash Caps',
                                            fontWeight: FontWeight.w700,
                                            height: 0.08,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 32,
                                      top: 119,
                                      child: SizedBox(
                                        width: 300,
                                        height: 43,
                                        child: Text(
                                          'pill check에서 갤러리 \n접근 권한을 허용해주시겠습니까?',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 17,
                                            fontFamily: 'Oleo Script Swash Caps',
                                            fontWeight: FontWeight.w400,
                                            height: 0.07,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 206,
                                      top: 210,
                                      child: Container(
                                        padding: const EdgeInsets.only(
                                          top: 14,
                                          left: 26,
                                          right: 23,
                                          bottom: 4,
                                        ),
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(color: Color(0xFF6A6A6A)),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            SizedBox(
                                              width: 80,
                                              height: 29,
                                              child: Text(
                                                '허용',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 20,
                                                  fontFamily: 'Oleo Script Swash Caps',
                                                  fontWeight: FontWeight.w700,
                                                  height: 0.05,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 32,
                                      top: 210,
                                      child: Container(
                                        padding: const EdgeInsets.only(
                                          top: 14,
                                          left: 22,
                                          right: 27,
                                          bottom: 4,
                                        ),
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(color: Color(0xFF6A6A6A)),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            SizedBox(
                                              width: 80,
                                              height: 29,
                                              child: Text(
                                                '거부',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 20,
                                                  fontFamily: 'Oleo Script Swash Caps',
                                                  fontWeight: FontWeight.w700,
                                                  height: 0.05,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 106,
                              top: 116,
                              child: Container(
                                width: 156,
                                height: 156,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 156,
                                        height: 156,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/156x156"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 156,
                                        height: 156,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            Container(
                                              width: 156,
                                              height: 156,
                                              decoration: BoxDecoration(color: Color(0xFFF62020)),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 156,
                                        height: 156,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/156x156"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 156,
                                        height: 156,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            Container(
                                              width: 156,
                                              height: 156,
                                              decoration: BoxDecoration(color: Color(0xFFE4E4E4)),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 46,
                              top: 297,
                              child: SizedBox(
                                width: 325,
                                height: 64,
                                child: Text(
                                  '사진 불러오기를 통해 알약을 \n인식해보세요 !',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 23,
                                    fontFamily: 'Oleo Script Swash Caps',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 91,
                      top: 719,
                      child: SizedBox(
                        width: 303,
                        height: 51,
                        child: Text(
                          '도움이 필요하신가요 ?',
                          style: TextStyle(
                            color: Color(0xFFA7A7A7),
                            fontSize: 22,
                            fontFamily: 'Oleo Script Swash Caps',
                            fontWeight: FontWeight.w400,
                            height: 0.04,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
