import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          (),
        ]),
      ),
    );
  }
}

class  extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 401,
          height: 858,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Expanded(
                child: Container(
                  width: double.infinity,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 401,
                        height: 858,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 401,
                              height: 858,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(color: Colors.white),
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 63,
                                    top: 311,
                                    child: SizedBox(
                                      width: 325,
                                      height: 64,
                                      child: Text(
                                        '사진 불러오기를 통해 알약을 \n인식해보세요 !',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 23,
                                          fontFamily: 'Oleo Script Swash Caps',
                                          fontWeight: FontWeight.w400,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 123,
                                    top: 130,
                                    child: Container(
                                      width: 156,
                                      height: 156,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 156,
                                              height: 156,
                                              decoration: BoxDecoration(
                                                image: DecorationImage(
                                                  image: NetworkImage("https://via.placeholder.com/156x156"),
                                                  fit: BoxFit.fill,
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 156,
                                              height: 156,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  Container(
                                                    width: 156,
                                                    height: 156,
                                                    decoration: BoxDecoration(color: Color(0xFFF62020)),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 156,
                                              height: 156,
                                              decoration: BoxDecoration(
                                                image: DecorationImage(
                                                  image: NetworkImage("https://via.placeholder.com/156x156"),
                                                  fit: BoxFit.fill,
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 156,
                                              height: 156,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  Container(
                                                    width: 156,
                                                    height: 156,
                                                    decoration: BoxDecoration(color: Color(0xFFE4E4E4)),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 85,
                                    top: 718,
                                    child: SizedBox(
                                      width: 303,
                                      height: 51,
                                      child: Text(
                                        '도움이 필요하신가요 ?',
                                        style: TextStyle(
                                          color: Color(0xFFA7A7A7),
                                          fontSize: 22,
                                          fontFamily: 'Oleo Script Swash Caps',
                                          fontWeight: FontWeight.w400,
                                          height: 0.04,
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              padding: const EdgeInsets.only(top: 41, right: 232),
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  SizedBox(
                                    width: 183,
                                    height: 52,
                                    child: Text(
                                      'Pill check',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 30,
                                        fontFamily: 'Oleo Script Swash Caps',
                                        fontWeight: FontWeight.w400,
                                        height: 0.06,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: 312,
                              height: 112,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Container(
                                      width: 312,
                                      height: 112,
                                      padding: const EdgeInsets.only(
                                        top: 67,
                                        left: 92,
                                        right: 92,
                                        bottom: 8,
                                      ),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: ShapeDecoration(
                                        color: Color(0xFFA2C9C6),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(20),
                                        ),
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          SizedBox(
                                            width: 128,
                                            height: 37,
                                            child: Text(
                                              '사진 불러오기',
                                              style: TextStyle(
                                                color: Colors.black,
                                                fontSize: 22,
                                                fontFamily: 'Oleo Script Swash Caps',
                                                fontWeight: FontWeight.w400,
                                                height: 0.04,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: 401,
                              height: 78,
                              padding: const EdgeInsets.only(top: 20, bottom: 21),
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 37,
                                    height: 37,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFFD9D9D9),
                                      shape: OvalBorder(),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
