import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          1(),
        ]),
      ),
    );
  }
}

class 1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 401,
          height: 858,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 401,
                  height: 858,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 401,
                          height: 858,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 401,
                                  height: 858,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(color: Colors.white),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 12,
                                        top: 385,
                                        child: Container(
                                          width: 377,
                                          height: 377,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 377,
                                                  height: 377,
                                                  decoration: BoxDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage("https://via.placeholder.com/377x377"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 377,
                                                  height: 377,
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 377,
                                                        height: 377,
                                                        decoration: BoxDecoration(color: Color(0x7FF62020)),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 377,
                                                  height: 377,
                                                  decoration: BoxDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage("https://via.placeholder.com/377x377"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 377,
                                                  height: 377,
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 377,
                                                        height: 377,
                                                        decoration: BoxDecoration(color: Color(0x7FE4E4E4)),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 18,
                                        top: 737,
                                        child: SizedBox(
                                          width: 171,
                                          height: 30,
                                          child: Text(
                                            'version 1.0',
                                            style: TextStyle(
                                              color: Color(0xFF9A9A9A),
                                              fontSize: 17,
                                              fontFamily: 'Oleo Script Swash Caps',
                                              fontWeight: FontWeight.w400,
                                              height: 0.14,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12,
                                        top: 141,
                                        child: SizedBox(
                                          width: 279,
                                          height: 59,
                                          child: Text(
                                            '화면 테마 설정',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 22,
                                              fontFamily: 'Oleo Script Swash Caps',
                                              fontWeight: FontWeight.w400,
                                              height: 0.11,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 401,
                                  height: 93,
                                  padding: const EdgeInsets.only(top: 41, right: 232),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 183,
                                        height: 52,
                                        child: Text(
                                          'Pill check',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 30,
                                            fontFamily: 'Oleo Script Swash Caps',
                                            fontWeight: FontWeight.w400,
                                            height: 0.06,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 780,
                                child: Container(
                                  width: 401,
                                  height: 78,
                                  padding: const EdgeInsets.only(top: 20, bottom: 21),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 37,
                                        height: 37,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFD9D9D9),
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 93,
                        child: Container(
                          width: 401,
                          height: 45,
                          padding: const EdgeInsets.only(top: 7, left: 15, bottom: 15),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(color: Color(0xFFBDBDBD)),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.end,
                            crossAxisAlignment: CrossAxisAlignment.end,
                            children: [
                              const SizedBox(width: 217),
                              SizedBox(
                                width: 151,
                                height: 23,
                                child: Text(
                                  '설정',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 17,
                                    fontFamily: 'Oleo Script Swash Caps',
                                    fontWeight: FontWeight.w400,
                                    height: 0.14,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 273,
                child: Container(
                  width: 349,
                  height: 143,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Color(0xFFE2E2E2)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 12,
                        top: 14,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFF7474),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 13,
                        top: 78,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/40x40"),
                              fit: BoxFit.fill,
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 78,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/40x40"),
                              fit: BoxFit.fill,
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 155,
                        top: 78,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/40x40"),
                              fit: BoxFit.fill,
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 226,
                        top: 78,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/40x40"),
                              fit: BoxFit.fill,
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 297,
                        top: 78,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/40x40"),
                              fit: BoxFit.fill,
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 83,
                        top: 14,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Color(0xFF4A4A4A),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 154,
                        top: 14,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 225,
                        top: 14,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Color(0x3F550074),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 296,
                        top: 14,
                        child: Container(
                          width: 40,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Color(0xFFF3F990),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14,
                        top: 54,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '기본',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 13,
                        top: 118,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '빨강/블랙',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 85,
                        top: 118,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '연두/초록',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 154,
                        top: 122,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '하늘/파랑',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 227,
                        top: 118,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '주황/갈색',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 299,
                        top: 118,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '클래식',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 54,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '블랙',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 154,
                        top: 54,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '화이트',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 226,
                        top: 54,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '퍼플',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 297,
                        top: 54,
                        child: SizedBox(
                          width: 38,
                          height: 18,
                          child: Text(
                            '엘로우',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 7,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.41,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 7,
                top: 230,
                child: SizedBox(
                  width: 100,
                  height: 35,
                  child: Text(
                    '배경색상',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 19,
                      fontFamily: 'ABeeZee',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 483,
                child: Container(
                  width: 349,
                  height: 58,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Color(0xFFE2E2E2)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 18,
                        child: SizedBox(
                          width: 103,
                          height: 35,
                          child: Text(
                            '글씨 크기',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 17,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.07,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 92,
                        top: 11,
                        child: Container(
                          width: 37,
                          padding: const EdgeInsets.only(top: 4, left: 8, right: 7, bottom: 9),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(color: Colors.white),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Transform(
                                transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                                child: Container(
                                  width: 22,
                                  height: 22,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFA0A0A0),
                                    shape: StarBorder.polygon(sides: 3),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 11,
                        child: Container(
                          width: 37,
                          padding: const EdgeInsets.only(top: 4, left: 8, right: 7, bottom: 9),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(color: Colors.white),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Transform(
                                transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                                child: Container(
                                  width: 22,
                                  height: 22,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFA0A0A0),
                                    shape: StarBorder.polygon(sides: 3),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 140,
                        top: 17,
                        child: SizedBox(
                          width: 50,
                          height: 34,
                          child: Text(
                            '폰트',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 17,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                              height: 0.07,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 90,
                top: 642,
                child: Container(
                  width: 221,
                  height: 45,
                  padding: const EdgeInsets.only(
                    top: 12,
                    left: 67,
                    right: 66,
                    bottom: 11,
                  ),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Color(0xFFDDD6D6),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      SizedBox(
                        width: 88,
                        height: 22,
                        child: Text(
                          '적용',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 26,
                            fontFamily: 'ABeeZee',
                            fontWeight: FontWeight.w400,
                            height: 0.03,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
