import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          (),
        ]),
      ),
    );
  }
}

class  extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 401,
          height: 858,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 401,
                height: 858,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 401,
                        height: 858,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 401,
                                height: 858,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Colors.white),
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 12,
                                      top: 385,
                                      child: Container(
                                        width: 377,
                                        height: 377,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/377x377"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Container(
                                                      width: 377,
                                                      height: 377,
                                                      decoration: BoxDecoration(color: Color(0x7FF62020)),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/377x377"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Container(
                                                      width: 377,
                                                      height: 377,
                                                      decoration: BoxDecoration(color: Color(0x7FE4E4E4)),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 46,
                                      top: 154,
                                      child: SizedBox(
                                        width: 117,
                                        height: 43,
                                        child: Text(
                                          '설정',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Color(0xFF676666),
                                            fontSize: 30,
                                            fontFamily: 'Oleo Script Swash Caps',
                                            fontWeight: FontWeight.w700,
                                            height: 0.06,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 214,
                                      child: Container(
                                        width: 401,
                                        height: 79,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: ShapeDecoration(
                                          color: Color(0x7FBBBBBB),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(width: 1, color: Colors.white),
                                          ),
                                        ),
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 67,
                                              top: 13.94,
                                              child: SizedBox(
                                                width: 221,
                                                height: 48.79,
                                                child: Text(
                                                  '화면 테마 설정',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 22,
                                                    fontFamily: 'Oleo Script Swash Caps',
                                                    fontWeight: FontWeight.w400,
                                                    height: 0.11,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 18,
                                              top: 30,
                                              child: Container(
                                                width: 33,
                                                height: 33,
                                                decoration: ShapeDecoration(shape: OvalBorder()),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 293,
                                      child: Container(
                                        padding: const EdgeInsets.only(
                                          top: 13.94,
                                          left: 17,
                                          right: 113,
                                          bottom: 16.26,
                                        ),
                                        clipBehavior: Clip.antiAlias,
                                        decoration: ShapeDecoration(
                                          color: Color(0x7FBBBBBB),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(width: 1, color: Colors.white),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            const SizedBox(width: 17),
                                            SizedBox(
                                              width: 221,
                                              height: 48.79,
                                              child: Text(
                                                '계정 설정',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 22,
                                                  fontFamily: 'ABeeZee',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0.11,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 372,
                                      child: Container(
                                        padding: const EdgeInsets.only(
                                          top: 13.94,
                                          left: 17,
                                          right: 113,
                                          bottom: 16.26,
                                        ),
                                        clipBehavior: Clip.antiAlias,
                                        decoration: ShapeDecoration(
                                          color: Color(0x7FBBBBBB),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(width: 1, color: Colors.white),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            const SizedBox(width: 17),
                                            SizedBox(
                                              width: 221,
                                              height: 48.79,
                                              child: Text(
                                                '버전 및 업데이트 확인',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 22,
                                                  fontFamily: 'Oleo Script Swash Caps',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0.11,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 18,
                                      top: 737,
                                      child: SizedBox(
                                        width: 171,
                                        height: 30,
                                        child: Text(
                                          'version 1.0',
                                          style: TextStyle(
                                            color: Color(0xFF9A9A9A),
                                            fontSize: 17,
                                            fontFamily: 'Oleo Script Swash Caps',
                                            fontWeight: FontWeight.w400,
                                            height: 0.14,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 401,
                                height: 93,
                                padding: const EdgeInsets.only(top: 41, right: 232),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 183,
                                      height: 52,
                                      child: Text(
                                        'Pill check',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 30,
                                          fontFamily: 'Oleo Script Swash Caps',
                                          fontWeight: FontWeight.w400,
                                          height: 0.06,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 780,
                              child: Container(
                                width: 401,
                                height: 78,
                                padding: const EdgeInsets.only(top: 20, bottom: 21),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 37,
                                      height: 37,
                                      decoration: ShapeDecoration(
                                        color: Color(0xFFD9D9D9),
                                        shape: OvalBorder(),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 93,
                      child: Container(
                        width: 401,
                        height: 45,
                        padding: const EdgeInsets.only(top: 7, left: 15, bottom: 15),
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(color: Color(0xFFBDBDBD)),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            const SizedBox(width: 217),
                            SizedBox(
                              width: 151,
                              height: 23,
                              child: Text(
                                '설정',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 17,
                                  fontFamily: 'Oleo Script Swash Caps',
                                  fontWeight: FontWeight.w400,
                                  height: 0.14,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
