import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          3(),
        ]),
      ),
    );
  }
}

class 3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 401,
          height: 858,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 401,
                height: 858,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 401,
                        height: 858,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 401,
                                height: 858,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Colors.white),
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 12,
                                      top: 385,
                                      child: Container(
                                        width: 377,
                                        height: 377,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/377x377"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Container(
                                                      width: 377,
                                                      height: 377,
                                                      decoration: BoxDecoration(color: Color(0x7FF62020)),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/377x377"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 377,
                                                height: 377,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Container(
                                                      width: 377,
                                                      height: 377,
                                                      decoration: BoxDecoration(color: Color(0x7FE4E4E4)),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 18,
                                      top: 737,
                                      child: SizedBox(
                                        width: 171,
                                        height: 30,
                                        child: Text(
                                          'version 1.0',
                                          style: TextStyle(
                                            color: Color(0xFF9A9A9A),
                                            fontSize: 17,
                                            fontFamily: 'Oleo Script Swash Caps',
                                            fontWeight: FontWeight.w400,
                                            height: 0.14,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 12,
                                      top: 141,
                                      child: SizedBox(
                                        width: 279,
                                        height: 59,
                                        child: Text(
                                          '버전 및 업데이트 확인',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 22,
                                            fontFamily: 'Oleo Script Swash Caps',
                                            fontWeight: FontWeight.w400,
                                            height: 0.11,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 24,
                                      top: 222,
                                      child: Container(
                                        width: 349,
                                        height: 472,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(color: Color(0x7FDDDDDD)),
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 14,
                                              top: 13,
                                              child: SizedBox(
                                                width: 318,
                                                height: 52,
                                                child: Text(
                                                  '-pill check의 현 버전은 1.0입니다\n',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 22,
                                                    fontFamily: 'Oleo Script Swash Caps',
                                                    fontWeight: FontWeight.w400,
                                                    height: 0.11,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 14,
                                              top: 190,
                                              child: SizedBox(
                                                width: 318,
                                                height: 104,
                                                child: Text(
                                                  '-12/26 version 업데이트 예정\n(version1.3)',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 22,
                                                    fontFamily: 'Oleo Script Swash Caps',
                                                    fontWeight: FontWeight.w400,
                                                    height: 0.11,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 19,
                                              top: 72,
                                              child: Container(
                                                width: 305,
                                                padding: const EdgeInsets.only(top: 3, left: 9, right: 9, bottom: 11),
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(color: Colors.white),
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    SizedBox(
                                                      width: 287,
                                                      height: 38,
                                                      child: Text(
                                                        '사진불러오기 권한허용을 업데이트 하였습니다.',
                                                        textAlign: TextAlign.center,
                                                        style: TextStyle(
                                                          color: Colors.black,
                                                          fontSize: 14,
                                                          fontFamily: 'Oleo Script Swash Caps',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0.27,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 19,
                                              top: 294,
                                              child: Container(
                                                width: 305,
                                                padding: const EdgeInsets.only(top: 3, left: 9, right: 9, bottom: 11),
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(color: Colors.white),
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    SizedBox(
                                                      width: 287,
                                                      height: 38,
                                                      child: Text(
                                                        '알약 커뮤니티 기능 생성',
                                                        textAlign: TextAlign.center,
                                                        style: TextStyle(
                                                          color: Colors.black,
                                                          fontSize: 14,
                                                          fontFamily: 'Oleo Script Swash Caps',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0.27,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 19,
                                              top: 353,
                                              child: Container(
                                                width: 305,
                                                padding: const EdgeInsets.only(top: 3, left: 9, right: 9, bottom: 11),
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(color: Colors.white),
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    SizedBox(
                                                      width: 287,
                                                      height: 38,
                                                      child: Text(
                                                        '사용자 프로필 기능 생성',
                                                        textAlign: TextAlign.center,
                                                        style: TextStyle(
                                                          color: Colors.black,
                                                          fontSize: 14,
                                                          fontFamily: 'Oleo Script Swash Caps',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0.27,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 20,
                                              top: 131,
                                              child: Container(
                                                width: 305,
                                                padding: const EdgeInsets.only(top: 3, left: 9, right: 9, bottom: 11),
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(color: Colors.white),
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    SizedBox(
                                                      width: 287,
                                                      height: 38,
                                                      child: Text(
                                                        '카카오톡/구글 로그인을 업데이트 하였습니다.',
                                                        textAlign: TextAlign.center,
                                                        style: TextStyle(
                                                          color: Colors.black,
                                                          fontSize: 14,
                                                          fontFamily: 'Oleo Script Swash Caps',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0.27,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 401,
                                height: 93,
                                padding: const EdgeInsets.only(top: 41, right: 232),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 183,
                                      height: 52,
                                      child: Text(
                                        'Pill check',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 30,
                                          fontFamily: 'Oleo Script Swash Caps',
                                          fontWeight: FontWeight.w400,
                                          height: 0.06,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 780,
                              child: Container(
                                width: 401,
                                height: 78,
                                padding: const EdgeInsets.only(top: 20, bottom: 21),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 37,
                                      height: 37,
                                      decoration: ShapeDecoration(
                                        color: Color(0xFFD9D9D9),
                                        shape: OvalBorder(),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 93,
                      child: Container(
                        width: 401,
                        height: 45,
                        padding: const EdgeInsets.only(top: 7, left: 15, bottom: 15),
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(color: Color(0xFFBDBDBD)),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            const SizedBox(width: 217),
                            SizedBox(
                              width: 151,
                              height: 23,
                              child: Text(
                                '설정',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 17,
                                  fontFamily: 'Oleo Script Swash Caps',
                                  fontWeight: FontWeight.w400,
                                  height: 0.14,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
